In [ ]:
"""

7.1 (Filling arrays) Fill a 2-by-3 array with ones, a 3-by-3 array with zeros and a 2- by-5 array with 7s.

"""

In [1]:
import numpy as np

In [16]:
# Fill a 2-by-3 array with ones
ones = np.ones((2, 3), dtype=int)

In [17]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
# a 3-by-3 array with zeros
zeros = np.zeros((3, 3), dtype=int)

In [19]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
sevens = np.full((2, 5), 7, dtype=int)

In [21]:
sevens

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])