In [ ]:
"""

7.13 (Research and Use Other Broadcasting Capabilities) Research the NumPy broadcasting rules, then create your own arrays 
to test the rules.

"""

In [18]:
import numpy as np

In [19]:
"""

Broadcasting a 1D Array to a 2D Array

This example shows how a 1D array a1 is added to a 2D array a2. NumPy automatically expands the 1D array along the rows of 
the 2D array to perform element-wise addition.

"""

a1 = np.array([1, 2, 3])
a2 = np.array([[4, 5, 6], [7, 8, 9]])

In [20]:
a3 = a1 + a2

In [21]:
a3

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [10]:
"""
Broadcasting in Conditional Operations

We may need to apply a condition to an entire array or a subset of it. Broadcasting can help to perform these operations 
efficiently without needing loops.

"""

ages = np.array([12, 24, 35, 45, 60, 72])
age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


In [11]:
"""

Broadcasting for Matrix Multiplication

In this example, each element of a 2D matrix is multiplied by the corresponding element in a broadcasted vector.

"""

matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


In [12]:
"""

Scaling Data with Broadcasting

Consider a real-world scenario where we need to calculate the total calories in foods based on the amount of fats, proteins and carbohydrates. Each nutrient has a specific caloric value per gram.

Fats: 9 calories per gram (CPG)
Proteins: 4 CPG
Carbohydrates: 4 CPG

/7.13.png

Left table shows the original data with food items and their respective grams of fats, proteins and carbs. The array 
[9, 4, 4] represents the caloric values per gram for fats, proteins and carbs respectively. This array is being broadcast 
to match the dimensions of the original data and arrow indicates the broadcasting operation.

Broadcasting array is multiplied element-wise with each row of the original data.
As a result right table shows the result of the multiplication where each cell represents the caloric contribution of that 
specific nutrient in the food item.

"""

food_data = np.array([[0.8, 2.9, 3.9], 
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])

caloric_values = np.array([9,4,4]) 

caloric_matrix = caloric_values 

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [496.8 126.8  95.6]
 [129.6  44.   19.6]]


In [13]:
"""

Adjusting Temperature Data Across Multiple Locations

Suppose you have a 2D array representing daily temperature readings across multiple cities and you want to apply a 
correction factor to each city’s temperature data.

"""
temperatures = np.array([
    [30, 32, 34, 33, 31],  
    [25, 27, 29, 28, 26], 
    [20, 22, 24, 23, 21]  
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


In [14]:
"""

Normalizing Image Data

Normalization is important in many real-world scenarios like image processing and machine learning because it:

Centers data by subtracting the mean by ensuring features have zero mean.
Scales data by dividing by the standard deviation by ensuring features have unit variance.
Improves numerical stability and performance of algorithms like gradient descent.
Let's see how broadcasting simplifies normalization:

"""

image = np.array([
    [100, 120, 130],
    [90, 110, 140],
    [80, 100, 120]
])

mean = image.mean(axis=0)   
std = image.std(axis=0)    

normalized_image = (image - mean) / std
print(normalized_image)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


In [17]:
"""

Centering Data in Machine Learning

Centering data is an important step in many machine learning workflows. Broadcasting helps center the data efficiently by 
subtracting the mean from each feature.

"""
data = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])

feature_mean = data.mean(axis=0)


centered_data = data - feature_mean
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
