In [ ]:
"""

7.14 (Horizontal and Vertical Stacking) Create the two-dimensional arrays 

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
c) Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.

"""

In [18]:
import numpy as np

In [19]:
array1 = np.array([[0, 1], [2, 3]])

In [20]:
array2 = np.array([[4, 5], [6, 7]])

In [21]:
# a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.vstack((array1, array2))
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
# b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
array4 = np.hstack((array1, array2))
array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [23]:
# c) Use vertical stacking with two copies of array4 to create a 4-by-4 array 5.
array5 = np.vstack((array4, array4))
array5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [24]:
# d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
array6 = np.hstack((array3, array3))
array6

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])