In [ ]:
"""

7.15 (Research and Use NumPy’s concatenate Function) Research NumPy function concatenate, then use it to reimplement the 
previous exercise.

7.14 (Horizontal and Vertical Stacking) Create the two-dimensional arrays 

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
c) Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.

"""

In [1]:
import numpy as np

In [2]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

In [5]:
# a)
array3 = np.concatenate((array1, array2), axis=0)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
# b)
array4 = np.concatenate((array1, array2), axis=1)
array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [7]:
# c) 
array5 = np.concatenate((array4, array4), axis=0)
array5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [8]:
# d) 
array6 = np.concatenate((array3, array3), axis=1)
array6

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])