In [ ]:
"""

7.2 (Broadcasting) Use arange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each of the 
following operations on the original array:

a) Cube every element of the array.
b) Add 7 to every element of the array.
c) Multiply every element of the array by 2.

"""

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 4).reshape(2, 2)

In [3]:
arr

array([[0, 1],
       [2, 3]])

In [6]:
# a) Cube every element of the array.
cube = arr ** 3

In [7]:
cube

array([[ 0,  1],
       [ 8, 27]])

In [8]:
# b) Add 7 to every element of the array.
add = arr + 7

In [9]:
add

array([[ 7,  8],
       [ 9, 10]])

In [10]:
# c) Multiply every element of the array by 2.
multiply = arr * 2

In [11]:
multiply

array([[0, 2],
       [4, 6]])