In [ ]:
"""

7.24 (AI Project: Introducing Heuristic Programming with the Knight’s Tour) An interesting puzzler for chess buffs is the 
Knight’s Tour problem, originally proposed by the mathematician Euler. Can the knight piece move around an empty chessboard 
and touch each of the 64 squares once and only once? We study this intriguing problem in depth here.
The knight makes only L-shaped moves (two spaces in one direction and one space in a perpendicular direction). Thus, as 
shown in the figure below, from a square near the middle of an empty chessboard, the knight (labeled K) can make eight 
different moves (numbered 0 through 7).

/7.24.png

a) Draw a neight-by-eight chessboard on a sheet of paper, and attempt a Knight’s Tour by hand. Put a 1 in the starting square,
a 2 in the second square, a 3 in the third, and so on. Before starting the tour, estimate how far you think you’ll get, 
remembering that a full tour consists of 64 moves. How far did you get? Was this close to your estimate?

b) Now let’s develop a script that will move the knight around a chessboard rep- resented by an eight-by-eight two-dimensional
array named board. Initialize each square to zero. We describe each of the eight possible moves in terms of its horizontal 
and vertical components. For example, a move of type 0, as shown in the preceding figure, consists of moving two squares 
horizontally to the right and one square vertically upward. A move of type 2 consists of moving one square horizontally to 
the left and two squares vertically upward. Horizon- tal moves to the left and vertical moves upward are indicated with 
negative numbers. The eight moves may be described by two one-dimensional arrays, horizontal and vertical, as follows:

/7.24.2.png

Let the variables current_row and current_column indicate the row and column, respectively, of the knight’s current position.
To make a move of type move_number (a value 0–7), your script should use the statements 

current_row += vertical[move_number] 
current_column += horizontal[move_number]

Write a script to move the knight around the chessboard. Keep a counter that varies from 1 to 64. Record the latest count in 
each square the knight moves to. Test each potential move to see if the knight has already visited that square. Test every 
potential move to ensure that the knight does not land off the chessboard. Run the application. How many moves did the 
knight make?

c) c) After attempting to write and run a Knight’s Tour script, you’ve probably developed some valuable insights. We’ll use 
these insights to develop a heuristic (i.e., a common-sense rule) for moving the knight. Heuristics do not guarantee success,
but a carefully developed heuristic greatly improves the chance of suc- cess. You may have observed that the outer squares
are more troublesome than the squares nearer the center of the board. In fact, the most troublesome or in- accessible squares
are the four corners.
Intuition may suggest that you should attempt to move the knight to the most troublesome squares first and leave open those 
that are easiest to get to so that when the board gets congested near the end of the tour, there will be a greater chance of 
success.
We could develop an “accessibility heuristic” by classifying each of the squares according to how accessible it is and always
moving the knight (using the knight’s L-shaped moves) to the most inaccessible square. We fill two- dimensional array 
accessibility with numbers indicating from how many squares each particular square is accessible. On a blank chessboard, 
each of the 16 squares nearest the center is rated as 8, each corner square is rated as 2, and the other squares have 
accessibility numbers of 3, 4 or 6 as follows:

/7.24.3.png

Write a new version of the Knight’s Tour, using the accessibility heuristic. The knight should always move to the square with
the lowest accessibility number. In case of a tie, the knight may move to any of the tied squares. Therefore, the tour may 
begin in any of the four corners. [Note: As the knight moves around the chessboard, your application should reduce the 
accessibility numbers as more squares become occupied. In this way, at any given time during the tour, each available 
square’s accessibility number will remain equal to precisely the number of squares from which that square may be reached.] 
Run this version of your script. Did you get a full tour? Modify the script to run 64 tours, one starting from each square 
of the chessboard. How many full tours did you get?

"""

In [38]:
import numpy as np

In [39]:
# a)
# My estimate was 64 moves.
# I could only go up to 23 moves.
# There is a huge difference in my estimate and acutal game.

In [202]:
# b)
board = np.array([0] * 64).reshape(8, 8)
print(board)
horizontal = np.array([2, 1, -1, -2, -2, -1, 1, 2])
vertical = np.array([-1, -2, -2, -1, 1, 2, 2, 1])
print(f'Horizonal Moves: {horizontal}')
print(f'Vertical Moves: {vertical}')
current_row = 0
current_column = 0
counter = 0
while True:
    old_row = current_row
    old_column = current_column
    for move_number in range(8):
        possible_row = current_row + vertical[move_number]
        possible_column = current_column + horizontal[move_number]
        if 0 <= possible_row <= 7 and 0 <= possible_column <= 7:
            if board[possible_row][possible_column] == 0:
                counter += 1
                board[current_row][current_column] = counter
                current_row += vertical[move_number] 
                current_column += horizontal[move_number]
                break

    if old_row == current_row and old_column == current_column:
        counter += 1
        board[current_row][current_column] = counter
        break
print(f'Maximum Moves : {counter}')
print(board)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
Horizonal Moves: [ 2  1 -1 -2 -2 -1  1  2]
Vertical Moves: [-1 -2 -2 -1  1  2  2  1]
Maximum Moves : 42
[[ 1 10 23 42  7  4 13 18]
 [24 41  8  3 12 17  6 15]
 [ 9  2 11 22  5 14 19 32]
 [ 0 25 40 35 20 31 16  0]
 [ 0 36 21  0 39  0 33 30]
 [26  0 38  0 34 29  0  0]
 [37  0  0 28  0  0  0  0]
 [ 0 27  0  0  0  0  0  0]]


In [191]:
# I could only go up to 41 moves

In [201]:
# c)
board = None
accessibility = None
horizontal = np.array([2, 1, -1, -2, -2, -1, 1, 2])
vertical = np.array([-1, -2, -2, -1, 1, 2, 2, 1])
current_row = None
current_column = None
counter = None

In [177]:
def initialize_game(row, column):
    """reset board and accessibility and current_row and column and counter"""
    global board, accessibility, current_row, current_column, counter
    board = np.array([0] * 64).reshape(8, 8)
    accessibility = np.array([
    [2, 3, 4, 4, 4, 4, 3, 2],
    [3, 4, 6, 6, 6, 6, 4, 3],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [3, 4, 6, 6, 6, 6, 4, 3],
    [2, 3, 4, 4, 4, 4, 3, 2]
])
    current_row = row
    current_column = column
    counter = 0

In [173]:
def update_accessibility(row, column):
    """this function update accessibility of given row and column"""
    for move_number in range(8):
        possible_row = row + vertical[move_number]
        possible_column = column + horizontal[move_number]

        if 0 <= possible_row <= 7 and 0 <= possible_column <= 7:
            old =  accessibility[possible_row, possible_column]
            accessibility[possible_row, possible_column] = (old - 1)

In [174]:
def lowest_accessibility_position(row, column):
    """this function return position of lowest accessibility square"""
    
    lowest_accessibility = None
    m_number = None
    
    for move_number in range(8):
        possible_row = row + vertical[move_number]
        possible_column = column + horizontal[move_number]
        
        if 0 <= possible_row <= 7 and 0 <= possible_column <= 7:
            
            if board[possible_row][possible_column] == 0:
                
                if lowest_accessibility == None:
                    m_number = move_number
                    lowest_accessibility = accessibility[possible_row][possible_column]
                    
                if lowest_accessibility > accessibility[possible_row][possible_column]:
                    
                    m_number = move_number
                    lowest_accessibility = accessibility[possible_row][possible_column]
                    
    return m_number

In [194]:
initialize_game(0, 0)

In [199]:
while True:
    move_number = lowest_accessibility_position(current_row, current_column)
    if move_number == None:
        counter += 1
        board[current_row][current_column] = counter
        break
    counter += 1
    board[current_row][current_column] = counter
    current_row += vertical[move_number] 
    current_column += horizontal[move_number]
    update_accessibility(current_row, current_column)
print(f'Maximum moves: {counter}\n')
print(board)

Maximum moves: 64

[[ 7 40  9 34  5 30 19 32]
 [10 35  6 55 20 33  4 29]
 [41  8 39 36 47 54 31 18]
 [38 11 58 53 56 21 28  3]
 [59 42 37 48 63 46 17 22]
 [12 49 62 57 52 25  2 27]
 [43 60 51 14 45 64 23 16]
 [50 13 44 61 24 15 26  1]]


In [ ]:
for row in range(8):
    for col in range(8):
        initialize_game(row, col)
        while True:
            move_number = lowest_accessibility_position(current_row, current_column)
            if move_number == None:
                counter += 1
                board[current_row][current_column] = counter
                break
            counter += 1
            board[current_row][current_column] = counter
            current_row += vertical[move_number] 
            current_column += horizontal[move_number]
            update_accessibility(current_row, current_column)
        print(f'Maximum moves: {counter}\n')
        print(board)