In [ ]:
"""

7.25 (Knight’s Tour Project: Brute-Force Approaches) In Part (c) of the previous exer- cise, we developed a solution to the 
Knight’s Tour problem. The approach used, called the “accessibility heuristic,” generates many solutions and executes 
efficiently.

As computers continue to increase in power, we’ll be able to solve more problems with sheer computer power and relatively 
unsophisticated algorithms. Let’s call this approach “brute-force” problem solving.

a) Use random-number generation to enable the knight to walk around the chessboard (in its legitimate L-shaped moves) at 
random. Your script should run one tour and display the final chessboard. How far did the knight get?

b) Most likely,the script in Part(a) produced a relatively short tour. Now modify your script to attempt 1,000,000 tours. 
Use a one-dimensional array to keep track of the number of tours of each length. When your script finishes attempting the 
1,000,000 tours, it should display this information in a neat tabular format. What was the best result?

c) Most likely, the script in Part(b) gave you some “respectable” tours, but no full tours. Now let your script run until it 
produces a full tour. [Caution: This version of the script could run for hours on a powerful computer.] Once again, keep a 
table of the number of tours of each length, and display this table when the first full tour is found. How many tours did 
your script attempt before pro- ducing a full tour? How much time did it take?

d) Compare the brute-force version of the Knight’s Tour with the accessibility-heuristic version. Which required a more 
careful study of the problem? Which algorithm was more challenging to develop? Which required more computer power? Could we 
be certain (in advance) of obtaining a full tour with the ac- cessibility-heuristic approach? Could we be certain 
(in advance) of obtaining a full tour with the brute-force approach? Argue the pros and cons of brute-force problem-solving 
in general.

"""

In [4]:
import numpy as np
import random

In [2]:
# a) 
board = None
horizontal = np.array([2, 1, -1, -2, -2, -1, 1, 2])
vertical = np.array([-1, -2, -2, -1, 1, 2, 2, 1])
current_row = None
current_column = None
counter = None

In [3]:
def initialize_game(row, column):
    """reset board and current_row and column and counter"""
    global board, current_row, current_column, counter
    board = np.array([0] * 64).reshape(8, 8)
    current_row = row
    current_column = column
    counter = 63

In [23]:
initialize_game(0, 0)
while True:
    old_row = current_row
    old_column = current_column
    possible_moves = []
    move_number = random.randrange(8)
    for move_number in range(8):
        possible_row = current_row + vertical[move_number]
        possible_column = current_column + horizontal[move_number]
        if 0 <= possible_row <= 7 and 0 <= possible_column <= 7:
            if board[possible_row][possible_column] == 0:
                possible_moves += [move_number]
                
    if possible_moves:
        random_number = random.randrange(len(possible_moves))
        selected_move = possible_moves[random_number]
        
        counter += 1
        board[current_row][current_column] = counter
        current_row += vertical[selected_move] 
        current_column += horizontal[selected_move]
    
    if old_row == current_row and old_column == current_column:
        counter += 1
        board[current_row][current_column] = counter
        break
        
print(f'Maximum Moves : {counter}')
print(board)

Maximum Moves : 44
[[ 1  0  0  6  9  0 27 14]
 [20  5  8  0 26 13  0 11]
 [ 0  2 19 42  7 10 15 28]
 [44 21  4 33 18 25 12  0]
 [ 3  0 43 22 41 16 29 24]
 [36 39 34 17 32 23  0  0]
 [ 0  0 37 40  0  0  0 30]
 [38 35  0  0  0 31  0  0]]


In [40]:
# b) 
counting_array = np.array([0] * 1001)

In [48]:
for _ in range(1000):
    initialize_game(0, 0)
    while True:
        old_row = current_row
        old_column = current_column
        possible_moves = []
        move_number = random.randrange(8)
        for move_number in range(8):
            possible_row = current_row + vertical[move_number]
            possible_column = current_column + horizontal[move_number]
            if 0 <= possible_row <= 7 and 0 <= possible_column <= 7:
                if board[possible_row][possible_column] == 0:
                    possible_moves += [move_number]
                    
        if possible_moves:
            random_number = random.randrange(len(possible_moves))
            selected_move = possible_moves[random_number]
            
            counter += 1
            board[current_row][current_column] = counter
            current_row += vertical[selected_move] 
            current_column += horizontal[selected_move]
        
        if old_row == current_row and old_column == current_column:
            counter += 1
            board[current_row][current_column] = counter
            break
            
    counting_array[counter] += 1

In [44]:
print('Value\tTours')
for index, value in enumerate(counting_array):
    if value != 0:
        print(f'{index:<5}\t{value:<5}')

Value	Tours
8    	1    
10   	2    
11   	5    
12   	1    
13   	4    
14   	4    
15   	3    
16   	6    
17   	3    
18   	15   
19   	10   
20   	12   
21   	12   
22   	18   
23   	12   
24   	21   
25   	17   
26   	14   
27   	21   
28   	28   
29   	20   
30   	31   
31   	34   
32   	32   
33   	41   
34   	41   
35   	31   
36   	39   
37   	38   
38   	38   
39   	38   
40   	48   
41   	41   
42   	39   
43   	39   
44   	37   
45   	37   
46   	33   
47   	21   
48   	26   
49   	24   
50   	20   
51   	10   
52   	7    
53   	8    
54   	7    
55   	7    
56   	3    
58   	1    


In [140]:
# c) 
def run_function():
    """running this code throught function to get %timeit"""
    global counter_array1, current_row, current_column, counter, board
    
    while True:
        initialize_game(0, 0)
        while True:
            old_row = current_row
            old_column = current_column
            possible_moves = []
            move_number = random.randrange(8)
            for move_number in range(8):
                possible_row = current_row + vertical[move_number]
                possible_column = current_column + horizontal[move_number]
                if 0 <= possible_row <= 7 and 0 <= possible_column <= 7:
                    if board[possible_row][possible_column] == 0:
                        possible_moves += [move_number]
                        
            if possible_moves:
                random_number = random.randrange(len(possible_moves))
                selected_move = possible_moves[random_number]
                
                counter += 1
                board[current_row][current_column] = counter
                current_row += vertical[selected_move] 
                current_column += horizontal[selected_move]
            
            if old_row == current_row and old_column == current_column:
                counter += 1
                board[current_row][current_column] = counter
                break

        counter_array1 = np.append(counter_array1, counter)
        if counter == 64:
            break

In [141]:
counter_array1 = np.array(-1)

In [142]:
run_function()

Here we go


In [127]:
# # After running this for hours I have to stop this without time usage result
values, frequencies = np.unique(counter_array1, return_counts=True)
print('Value\tTours')
for index, value in zip(values[1:],frequencies[1:]): # to ignore negative number
    print(f'{index:<5}\t{value:<5}')

Value	Tours
8    	258  
9    	196  
10   	737  
11   	613  
12   	1213 
13   	1005 
14   	1733 
15   	1561 
16   	2414 
17   	2076 
18   	3197 
19   	2885 
20   	3982 
21   	3626 
22   	4936 
23   	4712 
24   	5979 
25   	5728 
26   	7259 
27   	6903 
28   	8548 
29   	8128 
30   	9929 
31   	9297 
32   	10947
33   	10643
34   	12506
35   	11844
36   	13345
37   	12540
38   	13989
39   	13006
40   	14244
41   	12797
42   	13817
43   	12113
44   	12705
45   	10720
46   	11157
47   	8961 
48   	8533 
49   	6629 
50   	6069 
51   	4531 
52   	3828 
53   	2568 
54   	2040 
55   	1277 
56   	861  
57   	452  
58   	285  
59   	118  
60   	69   
61   	15   
62   	4    
63   	1    


In [ ]:
# d)

"""

Compare the brute-force version of the Knight’s Tour with the accessibility-heuristic version. 
Which required a more careful study of the problem?

Answer: accessibility-heuristic version

Which algorithm was more challenging to develop?

Answer: accessibility-heuristic version

Which required more computer power?

Answer: brute-force version

Could we be certain (in advance) of obtaining a full tour with the ac- cessibility-heuristic approach? 

Answer: Yes

Could we be certain (in advance) of obtaining a full tour with the brute-force approach?

Answer: No

Argue the pros and cons of brute-force problem-solving in general.

brute-force pros:

Less challenging to develop

brute-force cons:

Required more computer power
Not certain of obtaining a full tour
Not possible to debug
More time taking

accessibility-heuristic version pros:

Required less computer power
Certain of obtaining a full tour
Possible to debug
Less time taking

accessibility-heuristic version cons:

more challenging to develop

"""