In [ ]:
"""

7.5 (Flattening arrays with flatten vs. ravel) Create a 2-by-3 array containing the first six powers of 2 beginning with 2^0. 
Flatten the array first with method flatten, then with ravel. In each case, display the result then display the original 
array to show that it was unmodified.

"""

In [1]:
import numpy as np

In [22]:
arr = (2 ** np.arange(6)).reshape(2, 3)

In [23]:
arr

array([[ 1,  2,  4],
       [ 8, 16, 32]])

In [24]:
flatten = arr.flatten()

In [25]:
flatten

array([ 1,  2,  4,  8, 16, 32])

In [26]:
arr

array([[ 1,  2,  4],
       [ 8, 16, 32]])

In [27]:
ravel = arr.ravel()

In [28]:
ravel

array([ 1,  2,  4,  8, 16, 32])

In [29]:
arr

array([[ 1,  2,  4],
       [ 8, 16, 32]])